/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TabPane;


public class App extends Application {
    public void start(Stage pstage) {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("fxml/template.fxml"));

        try {
            loader.load();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println(e.getMessage());
            System.err.println("Failed to open fxml!");
            System.exit(1);
        }

        Scene sroot = new Scene(loader.getRoot(), 900, 600);
        sroot.getStylesheets().add("css/default-style.css");
        pstage.setScene(sroot);
        pstage.show();
    }
    
    public static void main(String[] args) {
        launch(args);
    }
}
